#!/usr/bin/env bash
# Configures localhost and facebook.com IP addresses

cp /etc/hosts /tmp/hosts

sed 's/127\.0\.0\.1[[:space:]]localhost/127.0.0.2 localhost/' /tmp/hosts \
| grep -v "facebook.com" > /tmp/hosts.new

echo "8.8.8.8 facebook.com" >> /tmp/hosts.new

cat /tmp/hosts.new > /etc/hosts
